### ISSUE TITLE
Question about main.py

### ISSUE THREAD

**Issue by wtl-lang** [wngh1187/ExU-Net#2]
In main.py line 177, one parameter 'process_id' for function 'run' is missing?

**Comment by wngh1187** [comment]
Thank you for your interest in our research.
We used pytorch's multiprocessing package to share the file system between gpus.
The "run" function in main.py called from the "spawn" function needs the process index.
Information related to this can be found at https://pytorch.org/docs/stable/_modules/torch/multiprocessing/spawn.html#spawn.

Additionally, we confirmed that training works when we run the run/triain.py file in the current code.
Do you have any problems running our code?

**Comment by wtl-lang** [comment]
Thank you, when I run the main.py, there is an error "the function run(line 37 in main.py) cannot be found in __main__", I move the function 'run' to another file, the code runs. Also, there are some errors about the "all_gather()", which makes the list can not be indexed. I run the code in one GPU, so I write below:
lists = all_gather(list)
lists_ = list[0]
for i in range(len(list_)):
     Finally, the code runs with no errors.

**Comment by wngh1187** [comment]
Thank you for checking.
Our code is based on a multi-GPU environment.
It seems that an error occurred to you because we did not consider the single GPU environment.
First of all, you can use the code as you modified it, and I will upload a single GPU code as soon as possible.
